version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn generate
      - run: yarn test
      - run: yarn deploy
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: patrickhuijten.github.io