name: Deploy to patrickhuijten.dev
on: 
  push:
    branches:
      - main
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ${{secrets.PROJECT_DIR}}/${{github.event.repository.name }}
            git checkout main
            git fetch --all
            git reset --hard origin/main
            rm .env
            echo STORYBLOK_TOKEN=${{secrets.STORYBLOK_TOKEN}} >> .env
            echo HOSTNAME=${{secrets.HOSTNAME}} >> .env
            echo STORYBLOK_ACCESS_TOKEN=${{secrets.STORYBLOK_ACCESS_TOKEN}} >> .env
            yarn
            rm -rf .next
            yarn storyblok login --region eu --token ${{secrets.STORYBLOK_ACCESS_TOKEN}}
            yarn storyblok:pull-components
            yarn storyblok:typegen
            yarn build
            pm2 kill
            pm2 start yarn --name next -- start
