name: GitHub Actions Demo
on: 
  push:
    branches:
      - main
jobs:
  Deploy-To-Server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ${{secrets.PROJECT_DIR}}/${{github.event.repository.name }}
            git checkout main
            git fetch --all
            git reset --hard origin/main
            rm .env
            echo STORYBLOK_TOKEN=${{secrets.STORYBLOK_TOKEN}} >> .env
            echo HOSTNAME=${{secrets.HOSTNAME}} >> .env
            cat .env
            yarn install
            rm -rf .next
            yarn build
            pm2 kill
            pm2 start yarn --name next -- start
            